version: "3"

services:
  telemetry-frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    # Copy in changes to the ui, so no need to rebuild the images.
    volumes:
      - /app/node_modules
      - ./packages:/app/packages
    ports:
      - 3000:80
    expose:
      - 3000
  telemetry-backend-shard:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    command: [
      'telemetry_shard',
      '--listen', '0.0.0.0:8001',
      '--core', 'http://telemetry-backend-core:8000/shard_submit'
    ]
    ports:
      - 8001:8001
    expose:
      - 8001
  telemetry-backend-core:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    command: [
      'telemetry_core',
      '--listen', '0.0.0.0:8000'
    ]
    ports:
      - 8000:8000
    expose:
      - 8000
